---
- hosts: webservers
  tasks:
   - name: Install forever
     npm: name=forever global=yes state=present

   - name: cloning the repo
     command: git clone https://github.com/anujdevopslearn/SonarQubeNodeJS.git

   - name: npm installation
     command: npm install
     args:
       chdir: ~/SonarQubeNodeJS

   - name: execute npm
     command: forever start /root/SonarQubeNodeJS/app/server.js
